name: LaTeX Output

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install LaTeX
      run: |
        sudo apt-get update && \
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texlive-latex-recommended texlive-lang-english

    - name: Compile LaTeX code
      run: pdflatex -interaction=nonstopmode -halt-on-error main.tex

    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: main.pdf
