name: Build and push PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install TeX Live
        run: sudo apt-get install texlive-full -y

      - name: Compile LaTeX code
        run: |
          pdflatex -interaction=nonstopmode main.tex
          pdflatex -interaction=nonstopmode main.tex

      - name: Copy PDF to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: main.pdf

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download previous PDF
        uses: actions/download-artifact@v2
        with:
          name: main
          path: prev_main.pdf

      - name: Compare PDF files
        run: |
          if ! cmp -s prev_main.pdf main.pdf; then
            echo "PDF files are different"
            echo "::set-env name=PDF_DIFF::true"
          else
            echo "PDF files are the same"
            echo "::set-env name=PDF_DIFF::false"
          fi

      - name: Configure git
        run: |
          git config --global user.email "<YOUR-EMAIL>"
          git config --global user.name "<YOUR-USERNAME>"

      - name: Commit and push changes
        if: env.PDF_DIFF == 'true'
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update PDF file"
          add: main.pdf
          branch: main
